import * as fs from 'fs';
import * as path from 'path';
import ExcelJS from 'exceljs';

interface TestResultEntry {
  suite: string;
  testName: string;
  status: 'passed' | 'failed' | 'skipped' | 'timedOut';
  duration: number;
  error?: string;
  retries: number;
  file: string;
  project: string;
}

interface PlaywrightJsonResult {
  suites: PlaywrightSuite[];
  stats: {
    startTime: string;
    duration: number;
    expected: number;
    unexpected: number;
    flaky: number;
    skipped: number;
  };
}

interface PlaywrightSuite {
  title: string;
  file: string;
  suites?: PlaywrightSuite[];
  specs?: PlaywrightSpec[];
}

interface PlaywrightSpec {
  title: string;
  ok: boolean;
  tests: PlaywrightTest[];
}

interface PlaywrightTest {
  projectName: string;
  results: PlaywrightTestResult[];
  status: string;
}

interface PlaywrightTestResult {
  status: string;
  duration: number;
  error?: { message: string };
  retry: number;
}

/**
 * Generates an Excel report from Playwright's JSON output.
 *
 * Run after tests:
 *   npx tsx src/reporters/generate-excel-report.ts
 *
 * Reads: ./reports/results.json (generated by Playwright json reporter)
 * Outputs: ./reports/test-report-{timestamp}.xlsx
 */
async function generateExcelReport(): Promise<void> {
  const jsonPath = path.resolve('./reports/results.json');

  if (!fs.existsSync(jsonPath)) {
    console.error('❌ No results.json found. Run tests first: npm test');
    process.exit(1);
  }

  const rawData = JSON.parse(fs.readFileSync(jsonPath, 'utf-8')) as PlaywrightJsonResult;
  const results = flattenResults(rawData);

  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Quantarra QA Automation';
  workbook.created = new Date();

  // --- Sheet 1: Summary ---
  const summarySheet = workbook.addWorksheet('Summary');
  addSummarySheet(summarySheet, rawData, results);

  // --- Sheet 2: Detailed Results ---
  const detailSheet = workbook.addWorksheet('Test Results');
  addDetailSheet(detailSheet, results);

  // --- Sheet 3: Failures Only ---
  const failures = results.filter((r) => r.status === 'failed' || r.status === 'timedOut');
  if (failures.length > 0) {
    const failSheet = workbook.addWorksheet('Failures');
    addFailuresSheet(failSheet, failures);
  }

  // --- Sheet 4: Per-Suite Summary ---
  const suiteSheet = workbook.addWorksheet('Suite Summary');
  addSuiteSummarySheet(suiteSheet, results);

  // Save
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const outputDir = './reports';
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const outputPath = path.join(outputDir, `test-report-${timestamp}.xlsx`);
  await workbook.xlsx.writeFile(outputPath);

  console.log(`\n📊 Excel report generated: ${outputPath}`);
  console.log(`   Total: ${results.length} | Passed: ${results.filter((r) => r.status === 'passed').length} | Failed: ${failures.length} | Skipped: ${results.filter((r) => r.status === 'skipped').length}`);
}

function flattenResults(data: PlaywrightJsonResult): TestResultEntry[] {
  const results: TestResultEntry[] = [];

  function walkSuite(suite: PlaywrightSuite, parentTitle: string): void {
    const suiteName = parentTitle ? `${parentTitle} > ${suite.title}` : suite.title;

    if (suite.specs) {
      for (const spec of suite.specs) {
        for (const test of spec.tests) {
          const lastResult = test.results[test.results.length - 1];
          results.push({
            suite: suiteName,
            testName: spec.title,
            status: lastResult?.status as TestResultEntry['status'] || 'skipped',
            duration: lastResult?.duration || 0,
            error: lastResult?.error?.message,
            retries: test.results.length - 1,
            file: suite.file || '',
            project: test.projectName || '',
          });
        }
      }
    }

    if (suite.suites) {
      for (const child of suite.suites) {
        walkSuite(child, suiteName);
      }
    }
  }

  for (const suite of data.suites) {
    walkSuite(suite, '');
  }

  return results;
}

function addSummarySheet(sheet: ExcelJS.Worksheet, data: PlaywrightJsonResult, results: TestResultEntry[]): void {
  sheet.columns = [
    { header: 'Metric', key: 'metric', width: 30 },
    { header: 'Value', key: 'value', width: 30 },
  ];

  const passed = results.filter((r) => r.status === 'passed').length;
  const failed = results.filter((r) => r.status === 'failed' || r.status === 'timedOut').length;
  const skipped = results.filter((r) => r.status === 'skipped').length;
  const totalDuration = results.reduce((sum, r) => sum + r.duration, 0);

  const rows = [
    { metric: 'Execution Date', value: new Date().toLocaleString() },
    { metric: 'Environment', value: process.env.ENV || 'dev' },
    { metric: 'Total Tests', value: results.length.toString() },
    { metric: 'Passed', value: passed.toString() },
    { metric: 'Failed', value: failed.toString() },
    { metric: 'Skipped', value: skipped.toString() },
    { metric: 'Pass Rate', value: `${((passed / (results.length - skipped)) * 100).toFixed(1)}%` },
    { metric: 'Total Duration', value: `${(totalDuration / 1000).toFixed(1)}s` },
    { metric: 'Avg Test Duration', value: `${(totalDuration / results.length / 1000).toFixed(2)}s` },
  ];

  rows.forEach((row) => sheet.addRow(row));

  // Style header row
  sheet.getRow(1).font = { bold: true };
  sheet.getRow(1).fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FF4472C4' },
  };
  sheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
}

function addDetailSheet(sheet: ExcelJS.Worksheet, results: TestResultEntry[]): void {
  sheet.columns = [
    { header: '#', key: 'index', width: 5 },
    { header: 'Suite', key: 'suite', width: 40 },
    { header: 'Test Name', key: 'testName', width: 50 },
    { header: 'Status', key: 'status', width: 12 },
    { header: 'Duration (s)', key: 'duration', width: 14 },
    { header: 'Retries', key: 'retries', width: 8 },
    { header: 'Project', key: 'project', width: 15 },
    { header: 'File', key: 'file', width: 50 },
  ];

  results.forEach((r, i) => {
    const row = sheet.addRow({
      index: i + 1,
      suite: r.suite,
      testName: r.testName,
      status: r.status.toUpperCase(),
      duration: (r.duration / 1000).toFixed(2),
      retries: r.retries,
      project: r.project,
      file: r.file,
    });

    // Color-code status
    const statusCell = row.getCell('status');
    if (r.status === 'passed') {
      statusCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFC6EFCE' } };
      statusCell.font = { color: { argb: 'FF006100' } };
    } else if (r.status === 'failed' || r.status === 'timedOut') {
      statusCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFC7CE' } };
      statusCell.font = { color: { argb: 'FF9C0006' } };
    } else if (r.status === 'skipped') {
      statusCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFF2CC' } };
      statusCell.font = { color: { argb: 'FF9C6500' } };
    }
  });

  // Style header
  sheet.getRow(1).font = { bold: true };
  sheet.getRow(1).fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FF4472C4' },
  };
  sheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };

  // Auto-filter
  sheet.autoFilter = { from: 'A1', to: 'H1' };
}

function addFailuresSheet(sheet: ExcelJS.Worksheet, failures: TestResultEntry[]): void {
  sheet.columns = [
    { header: '#', key: 'index', width: 5 },
    { header: 'Test Name', key: 'testName', width: 50 },
    { header: 'Suite', key: 'suite', width: 40 },
    { header: 'Error Message', key: 'error', width: 80 },
    { header: 'Duration (s)', key: 'duration', width: 14 },
    { header: 'File', key: 'file', width: 50 },
  ];

  failures.forEach((f, i) => {
    sheet.addRow({
      index: i + 1,
      testName: f.testName,
      suite: f.suite,
      error: (f.error || 'Unknown').substring(0, 500),
      duration: (f.duration / 1000).toFixed(2),
      file: f.file,
    });
  });

  sheet.getRow(1).font = { bold: true };
  sheet.getRow(1).fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FFFF0000' },
  };
  sheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
}

function addSuiteSummarySheet(sheet: ExcelJS.Worksheet, results: TestResultEntry[]): void {
  sheet.columns = [
    { header: 'Suite', key: 'suite', width: 50 },
    { header: 'Total', key: 'total', width: 8 },
    { header: 'Passed', key: 'passed', width: 8 },
    { header: 'Failed', key: 'failed', width: 8 },
    { header: 'Skipped', key: 'skipped', width: 8 },
    { header: 'Pass Rate', key: 'passRate', width: 12 },
    { header: 'Avg Duration (s)', key: 'avgDuration', width: 16 },
  ];

  // Group by suite
  const suiteMap = new Map<string, TestResultEntry[]>();
  results.forEach((r) => {
    const existing = suiteMap.get(r.suite) || [];
    existing.push(r);
    suiteMap.set(r.suite, existing);
  });

  suiteMap.forEach((tests, suite) => {
    const passed = tests.filter((t) => t.status === 'passed').length;
    const failed = tests.filter((t) => t.status === 'failed' || t.status === 'timedOut').length;
    const skipped = tests.filter((t) => t.status === 'skipped').length;
    const runnable = tests.length - skipped;
    const avgDuration = tests.reduce((sum, t) => sum + t.duration, 0) / tests.length;

    sheet.addRow({
      suite,
      total: tests.length,
      passed,
      failed,
      skipped,
      passRate: runnable > 0 ? `${((passed / runnable) * 100).toFixed(1)}%` : 'N/A',
      avgDuration: (avgDuration / 1000).toFixed(2),
    });
  });

  sheet.getRow(1).font = { bold: true };
  sheet.getRow(1).fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FF4472C4' },
  };
  sheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
  sheet.autoFilter = { from: 'A1', to: 'G1' };
}

// Run
generateExcelReport().catch((err) => {
  console.error('❌ Report generation failed:', err);
  process.exit(1);
});
